### ISSUE TITLE
Support Bulk upload API (Telemetry upload)

### ISSUE THREAD

**Issue by joel-ekstep** [projectOpenRAP/OpenRAP#30]
As there are going to be multiple small telemetry files, we need to have a way to upload many telemetry files at one go.

**Comment by joel-ekstep** [comment]
Sunbird platform has requested if we are able to cap the total size of files uploaded via one API call to 100 MB.

@pronoy-debnath Is that doable?

**Comment by pronoy-debnath** [comment]
I think restriction can be put either on client or on server side. But ideally it should be on server side.
For telemetry bulk update api, openRAP will be a client. And we can control the size before we sent data to server.
But for this approach every client should take care of it individually. I mean, in future, if mobile app also uses bulkapi, it will need to implement the logic.
Nonetheless, we will take care of it in openRAP code.

**Comment by joel-ekstep** [comment]
For the sake of clarity, what are the reasons why it should be restricted on server side?
If there is a restriction on server side - it might not accept files that are larger. Wouldn't that be more inefficiency than asking the client to do some size control?

Are there certain concerns regarding client packaging that we could address?

**Comment by pronoy-debnath** [comment]
There is no hard and fast rule. But the best practice is that server shouldn't take anything for granted.
In future, we might not have control on all types of clients that will access such apis.

Since telemetry bulk api will only be used for telemetry upload and not regular files, if should not block larger regular files.

Anyway, I meant to implement it on openRAP client side irrespective of server.
